### ISSUE TITLE
Set up cypress for E2E testing

### ISSUE THREAD

**Issue by capsulecorplab** [AutarkLabs/planning-suite#108]
## Steps for Cypress Setup

- [x] Research whether or not a web3 provider can be injected into a Cypress environment - **It can be done**
- [x] Set up web3-injected Cypress with the [Aragon React Boilerplate App](https://github.com/aragon/aragon-react-kit-boilerplate) and get blockchain transactions working in this simplified environment
- [x] Set up some basic Cypress tests with the Address Book App
- [x] Teach the team to Write Cypress tests
- [ ] Begin to set up Cypress with the Rewards app as we begin to develop and concurrently integrate it!
- ~Get Cypress running in TravisCI~  - created #520 to track this

## Out of the Scope of this issue
- Detailed test flow for existing apps, like below. The immediate purpose of this implementation is to accelerate our workflows for new development

https://www.cypress.io/
https://docs.cypress.io/guides/getting-started/installing-cypress.html#npm-install

Primary flow:
* Open the Allocations App
  * Click the “New Account” button
  * Enter a name and limit, then create the Account
  * The Allocations app should now display a card for the newly created account
  * Use Metamask to transfer ETH into the address of this newly created account (as the Allocation will draw from this balance). Make sure to transfer enough eth to cover the upcoming allocation. (this step can be done after voting, but must be done before executing the vote)
  * Click the context menu for the Account, then select “New Allocation”
  * Enter the Allocation description, then select “Token Transfer”.
  * Input an Amount for the allocation.
  * Enter the options.
    * The options should be valid Ethereum addresses. Click the “+” to include the option.
  * After submitting the Allocation it will forward it to the Range Voting app
* Open the Range Voting App
  * Click on the new range vote
  * Cast a vote
  * After the range vote ends (the time is up), anyone in the DAO can click the “Execute Vote” action which tallies the votes.
* Open the Allocations App
  * Click the context menu for the Account, then select “Execute Payout”
  * This will distribute the tokens/ETH based on the results of the range vote.

Note: current bug in #236

**Comment by stellarmagnet** [comment]
Otto, let's not worry about cypress until we have finished all of the Milestone 2 work. But assigning you to this issue as well since you are interested in beginning implementation.
