### ISSUE TITLE
Disable the github bot

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#1124]
1) Disable github bot until we have deep linking
2) Regardless, always disable the Github in the dev environment (unless we are testing the bot)

Otherwise our repos get cluttered with "test" comments like below:

![image](https://user-images.githubusercontent.com/2584493/61445665-19636b80-a94e-11e9-8895-71695760ed7a.png)

**Comment by ottodevs** [comment]
This issue seems to be solved, @stellarmagnet feel free to re-open if you feel something is missing, I close it for now.
