### ISSUE TITLE
Dot voting won't load after 1.0.4 update

### ISSUE THREAD

**Issue by lkngtn** [AutarkLabs/planning-suite#1190]
![image](https://user-images.githubusercontent.com/4986634/63893116-52fcad00-c9b7-11e9-88ee-e5bfad7c99a5.png)

![image](https://user-images.githubusercontent.com/4986634/63893136-5b54e800-c9b7-11e9-82c4-ab19b70d971e.png)

**Comment by rkzel** [comment]
I have published new version of DV right now and propagated it. Version number is 1.0.5. As far as I can see 1.0.4 should be only in staging environment and why it got published to Rinkeby is what I'm investigating now.
After upgrading to 1.0.5 the DAO has working DV again :) Please let me know if I can close the ticket.

**Comment by lkngtn** [comment]
Yup seems to be working for us now. Thanks for the quick response!
