### ISSUE TITLE
Connect remaining events in RangeVoting

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/planning-suite#149]
Once the initial work is done for the StartVote event connecting the remaining events should be much simpler. It is necesary to make sure that the CastVote, UpdateCandidateSupport, ExecuteVote, and ChangeCandidateSupport events all update the front end information appropriately. I’m not sure if/where we’re storing the CandidateSupport value so this may be a little different but for the most part this just requires updating the vote information the same way the StartVote event creates the vote data initially and should rely on the same general function flow. The helper functions should be coded in such a way that they can work for all state changes.

**Comment by topocount** [comment]
@Quazia what's the current state of this?
