### ISSUE TITLE
Add additional events/event handling for Allocations app/contract

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/planning-suite#152]
Right now only the initial Allocation event is triggering changes in data, there’s a proxy contract setup to allow people to change the allocations for now so that it will work without the vault but this doesn’t properly update the balance right now. For this issue it’s necesary to make sure that any state change on the Allocations contract is triggering an event and that event is being properly caught and handled within the script.js of the Allocations app.

**Comment by topocount** [comment]
Functions missing events:

1. setDistribution
2. fund

**Comment by topocount** [comment]
@stellarmagnet I'm trying to figure out the UI workflow for funding these allocations, and I'm not sure where else the funding would go. Would clicking on the proxy address open up a transaction to send funds to that address?
