### ISSUE TITLE
Token Transfer UI not displaying correct options

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/planning-suite#166]
![changesallocations](https://user-images.githubusercontent.com/6549550/46627568-de075700-cb08-11e8-915a-d6ea6825b3a8.png)
Right now the additional options needed for a token transfer arn't in the UI.
For a more detailed look check the [invision](https://projects.invisionapp.com/d/main/default/#/console/14716432/306010959/preview).

I believe this were implemented at one point but may have been lost in the shuffle. We need this information though. I can handle connecting the options to the transaction if needed but at minimum we need entry fields for these additional options in the UI.

**Comment by rkzel** [comment]
New issue-specific branch created, partially working.
