### ISSUE TITLE
Allocations app: Currency dropdowns are inconsistent with other Aragon apps

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#175]
This is a comparison between the Finance app and the Allocations app (New Account) UI. You can see the font sizes are different. We need to ensure we are consistent with other Aragon apps.

![image](https://user-images.githubusercontent.com/2584493/46826628-52313d00-cd4b-11e8-8d8a-d46d33a3cf27.png)

**Comment by rkzel** [comment]
Specific setting giving 12px size to fonts was commented out in most recent changes - if now the fonts (in forms) are ok, this issue can be closed.
