### ISSUE TITLE
Enhance the No Data UI for Range Voting app

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#180]
**Range Voting Empty State**
- [x] Replace the icon https://www.dropbox.com/s/4doz5ganxodos4n/new_range_vote.svg?dl=0
- [x] Rename the button "Open Allocations" and the action should open the Allocations app
- [x] Update the card (title) -- make sure to include the period!--> `You have not created any range votes.`
- [x] Update the card (text) -- make sure to include the period!-->  `Use the Allocations app to get started.`
- [x] The card should be centered on the screen

**New Account**
- [x] Limit input field is too big

**Range Voting - Side panel**
- [x] Need to truncate the creator address
- [x] include the 'title' tooltip that shows full Creator address on hover - like in Accounts.js. We can make it fancier in future.

**Comment by ottodevs** [comment]
Ready for review
