### ISSUE TITLE
Use blockExplorerUrl() from @aragon/ui for etherscan URL

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#182]
Our apps do not have the proper logic for the etherscan URL. We should follow standard conventions of other Aragon apps.

Please double check all of our apps, see if it is using etherscan, and update as appropriate
- [ ] Projects app
- [ ] Allocations app
- [ ] Range Voting app
- [ ] Address Book app

see here - https://app.zenhub.com/workspaces/all-aragon-repos-5996d0a88c7c6963f4a4dfdc/issues/aragon/aragon/457

**Comment by ottodevs** [comment]
The etherscanBaseURL is getting pulled from an environment variable in Aragon's Survey App, we should maybe take the same approach: https://github.com/aragon/aragon-apps/blob/ced3a611c394de9f51a38e7f1df580b576940037/apps/survey/app/src/App.js#L19

**Comment by ottodevs** [comment]
Solved at #536
