### ISSUE TITLE
Improve issues with number of zeros displayed for token balances

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#205]
For the side panel in Range Vote (# voting tokens) and the Account cards in Allocations page (balance), we need an elegant solution for the number of zeros/"token decimals" etc that are displayed, so its consistent and also aligns with norms.

(there is currently an implementation for this, but it's not the elegant solution)

**Comment by Quazia** [comment]
Should be addressed in PR #474
