### ISSUE TITLE
Slider issues: sum of slider values > 100% when maxed out

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/planning-suite#209]
In a range vote, sometimes when all sliders are maxed out, the transaction will fail as the total voting tokens passed after finding the values from the slider is more tokens than the voter has available. 

This has something to do with the rounding and slider values.

**Comment by stellarmagnet** [comment]
@Quazia @topocount can we test if this issue still exists?

**Comment by Quazia** [comment]
It does, solution is to use the Aragon UI slider component but it'll take some logic re-work
