### ISSUE TITLE
Range Voting: Participation percentage - round up to two decimal places (side panel)

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#210]
Range voting landing page & voting panel:

Need to round up the participation percentage to two decimal places. e.g. 92.08% 

![image](https://user-images.githubusercontent.com/2584493/47249067-273a8f00-d3c4-11e8-8a38-91a1639461fd.png)

![image](https://user-images.githubusercontent.com/2584493/47249079-518c4c80-d3c4-11e8-81f1-49b1f6b200c2.png)

**Comment by Quazia** [comment]
This should be resolved in #244

**Comment by stellarmagnet** [comment]
Missing in the side panel (shows decimals)
![image](https://user-images.githubusercontent.com/2584493/52492871-69354e00-2bca-11e9-8b28-8ca586fd85f2.png)

**Comment by Quazia** [comment]
Should be addressed in PR #474
