### ISSUE TITLE
User should not be able to submit a new allocation that exceeds the limit of the account

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#214]
Right now, I can still "sign transaction" when doing a token transfer vote and the Allocation Amount is greater than the Account Limit. We shouldn't even allow it to get to that stage, there should be validation before

**Comment by topocount** [comment]
@stellarmagnet can you lay out your steps and the workflow that causes this to arise?

**Comment by Quazia** [comment]
This is now handled in the UI and the backend addressed in #244
