### ISSUE TITLE
Get Allocations tests Passing

### ISSUE THREAD

**Issue by topocount** [AutarkLabs/planning-suite#215]
Allocations Tests are failing after some significant rework to the range-voting app. We should get them passing again to get our coverage back up.

**Comment by ottodevs** [comment]
Hey @topocount !
I fixed trivial problems in Allocations tests and skipped failing Range-Voting tests, this way we should get a green in CI and coverage that let us focus into gradually fixing the skipped tests.
We had some problems also with coverage config and some imports in range-voting

**Comment by topocount** [comment]
Ha I just saw this after putting all the fixes in tonight. saves me the trouble of putting another PR together at least

**Comment by topocount** [comment]
I noticed some of the key logic wasn't reimplemented in the PR that Quazia had taken out. I got this reimplemented and passing, so I'll go ahead and push my changes and then we can merge these changes in together later
