### ISSUE TITLE
[Allocations] Increase efficiency of runPayout require guard

### ISSUE THREAD

**Issue by ottodevs** [AutarkLabs/planning-suite#216]
### https://github.com/Giveth/planning-app/blob/b517470cf19f63e15d7447b886c36abd87446f56/apps/allocations/contracts/Allocations.sol#L214

Since we may want to exit soon if the requires don't meet, I think it is a good idea to move lines 214-223 to line 207 (just after payout declaration)

We are always running a `for` loop that lot of times will be unneeded

**Comment by Quazia** [comment]
Good catch, feel free to bundle this hotfix into another issue branch as long as you tag this issue in the PR.

**Comment by topocount** [comment]
I just made these changes in branch #305 along with a few other things. Is it alright if I snag this issue?
