### ISSUE TITLE
Projects App v1 - Frontend

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#222]
All of the front-end required for Milestone 2.

**Comment by Quazia** [comment]
Most of the frontend has been built out and the github integration is handled. The main task that remains is getting all of the queries built so that the data on the frontend is populating through githubs GraphQL.

**Comment by ottodevs** [comment]
Completed first flow with graphql queries at: https://github.com/spacedecentral/planning-suite/pull/255

* I don't find the button to connect the new PR with the issue, so I report the link in this message.
(It seems that github only allows 1 to 1 PR-Issue connection)
