### ISSUE TITLE
Projects app [Issue curation] - Backend

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#223]
- Projects app requires a new action that allows the user to curate issues (see - https://docs.google.com/document/d/1Ub332Ad8aRXmJJ7klWoQ2ogHLdYy8fzE5RrKkUnKd6A/edit#heading=h.vx1227)
- This will forward the action to the range voting app, as an informational vote (see - https://docs.google.com/document/d/1Ub332Ad8aRXmJJ7klWoQ2ogHLdYy8fzE5RrKkUnKd6A/edit#heading=h.3l18frh)
- Check out the designs here under the Projects and Range Voting sections - https://invis.io/XHM4USVDAZR

**Comment by Quazia** [comment]
Range Voting <-> Projects synergy is the only remaining element here which should be in testing phases.

**Comment by topocount** [comment]
I also need to make sure Allocations forwarding still works, don't I?

**Comment by Quazia** [comment]
Yeah but I wouldn't put that under this issue.
