### ISSUE TITLE
Projects app [Issue curation] - Web3

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#224]

**Comment by ottodevs** [comment]
Partially being addressed at: https://github.com/spacedecentral/planning-suite/commit/4705233a3a88d345250cbddb988e9634388e0d12 and https://github.com/spacedecentral/planning-suite/commit/9c33858ae7d27aede91a9cc2cc41b56e19ecf5d0
Though it probably needs more work to be polished
