### ISSUE TITLE
Range Voting - Voting Results are not being reflected in the bar component

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#235]
This is an issue on both the range voting landing page and the side panel.

![image](https://user-images.githubusercontent.com/2584493/47595759-31d7c400-d982-11e8-9987-0c8424dbeeaf.png)

**Comment by Quazia** [comment]
This is resolved on the sidepanel, for the main page it requires moving to another app and then back again. Seems to be an issue with the way props are being handled/a lack of re-rendering when the vote status updates. UI issue @ottodevs please resolve.
