### ISSUE TITLE
Primary flow not working when voting with the same account that creates the allocation

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#236]
We need to make sure to test the primary flow with the latest code -- have been unable to execute a vote or execute a payout.

UPDATE: Kevin and I met yesterday and it seemed that the reason I wasn't able to execute the vote / payout was because I was performing the vote with the same account that created the Allocation vote.

**Comment by Quazia** [comment]
Are you voting with an account that has voting tokens?

**Comment by Quazia** [comment]
I cannot replicate this error.
