### ISSUE TITLE
Ability to add repos for organizations as well as individuals [Projects app]

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/planning-suite#280]
Currently, the only repos you can add within a DAO are personal public repos. We need the ability to add repos that are organizations or repos that an individual is part of as well as just personal repos.

This will probably involve changing the github query but if it's more complicated detail the blockers.

**Comment by stellarmagnet** [comment]
Compare this: https://github.com/stellarmagnet?tab=repositories

To this image:
![image](https://user-images.githubusercontent.com/2584493/51557221-27b64c00-1e31-11e9-8d56-c0cf2daab2ad.png)
