### ISSUE TITLE
URL for the Eth address linked on Address Book is incorrect, plus missing the copy action

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#289]
- The URL links to IPFS instead of Etherscan
- Copy icon is missing (which copies the address)

http://aragon.rinkeby.aragonpm.com/#/nwo.aragonid.eth/0x9bf27609f2f2642b36b29c4392ecb6d22775db55

**Comment by stellarmagnet** [comment]
Looks like the url is just # right now...

Probably want to follow what we did for Allocations app, until we have the solution that populates the subdomain plugged in...

https://github.com/spacedecentral/planning-suite/blob/dev/apps/allocations/app/components/Card/Account.js

**Comment by ottodevs** [comment]
Solved at: d37a143

**Comment by ottodevs** [comment]
@stellarmagnet could you please provide the svg file with the copy icon? at the invisionapp it is only available as a shape, instead of a downloadable asset.

**Comment by ottodevs** [comment]
Solved the copy part at 8f11885

**Comment by stellarmagnet** [comment]
Working now, I should create a new issue though so there is some indicator that says the address was copied
