### ISSUE TITLE
Projects app - Request Assignment panel (front-end)

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#290]
https://projects.invisionapp.com/d/main/default/#/console/14716432/314054578/preview
https://projects.invisionapp.com/d/main/default/#/console/14716432/314054577/preview

If possible work on #269 can be done in parallel.

**Comment by Quazia** [comment]
https://projects.invisionapp.com/d/main/default/#/console/14716432/314054578/preview
https://projects.invisionapp.com/d/main/default/#/console/14716432/314054577/preview

**Comment by stellarmagnet** [comment]
This FE is very similar to the #292 panel
