### ISSUE TITLE
Projects App [Bounty Allocation] - Connect frontend to contract

### ISSUE THREAD

**Issue by ottodevs** [AutarkLabs/planning-suite#296]
In projects App.js component there should be a function called `onSubmitBountyAllocation` that calls the contract function is missing right now, so the Allocation Bounty is not able to be submitted by submitting the form at the SidePanel

- [x] Create frontend hooks for transaction call
- [x] Prepare data in front end for transaction call
- [x] Add vault to projects contract
- [x] Connect transaction call to contract
- [x] Connect IPFS
- [ ] handle IPFS data

### Acceptance Testing
The ticket will be considered complete after the following scenarios are accomplished.
- [ ] The Settings translate as expected to how the Bounty Value is calculated in the New Bounty panel
- [x] After a New Bounty is submitted, the Bounty Value and proper bounty status color are accurately reflected in the row for the Issue.
- [ ] This color of the Bounty Value on the Issue row is updated as the bounty proposal moves through the various stages (Pending / Approved - Ready for assignment / Rejected / Completed)
- [x] The currency options available in the Settings page dropdown accurately reflect the currencies in the Organization's Vault
- [ ] Clearing the application cache should not result in buggy state issues, such as the bounty value disappearing on the issues page

**Comment by ottodevs** [comment]
Created the function and prepared the call to the contract. We need to define how we get IPFS hashes to call the contract function (but that may probably fall into another issue)

**Comment by Quazia** [comment]
@ottodevs  Let me know if you made any more progress and where you're at with this. I'd like to take a look at this first thing Tuesday unless the status has changed.

**Comment by stellarmagnet** [comment]
Has the UI been developed to display the bounty amount in the rows for the different statuses? I just want to make sure we don't forget about that integration.
