### ISSUE TITLE
Allocations - Execute payout doesn't work when the payouts are being sent to other Allocations Accounts

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#305]
UPDATE:
I have tested that this works now when sending to regular Ethereum addresses, but it does not work when I am trying to send to Allocations Accounts.

Is this because of gas issues? 4 months ago it worked when sending to allocations accounts, I think we have to figure out what is causing this.

OLD TEXT:
script.js breaks after a completed, voted-on allocation payout is executed

clearing the caches shows the new allocations screen, so that executePayout event is causing a logjam in script.js

**Comment by topocount** [comment]
"Execute Payout" in the UI is hooked up to "runPayout" on the contract. The event thrown by runPayout is not handled in the script.js "reducer" we have and this causes issues. It looks like the __PayoutExecuted__ event isn't handled in that reducer at all.

**Comment by topocount** [comment]
I commented out the PayoutExecuted event on Allocations.sol, but still saw the same behavior in the frontend where all frontend state stops pulling after runpayout is called. This has me stumped

I also tried handling cases where no cases are called, and the nextState returns as null, but that didn't do anything to alter behavior

**Comment by stellarmagnet** [comment]
closing - will be covered in #204
