### ISSUE TITLE
Range Voting - Options should display the human-readable Address Book name

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#310]
Right now when creating a New Allocation and enabling the address book, the expected behavior is that the address book entry names should be displayed in the Range Voting app, not the hashes.

**Comment by Quazia** [comment]
This is non-trivial and would require connecting the address book into the Range Voting, this is related to the whole cross app UX stuff. It's doable but I think the value add should make it low priority.
