### ISSUE TITLE
Projects App - Issue Curation - Connect front-end to backend

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#311]
- Navigate to Projects Issues tab
- Select multiple issues
- Click actions menu and select "Curate Issues"

Right now the issue curation isn't hooked up to the backend

**Comment by ottodevs** [comment]
Pending backend connection until better discussing the solidity approach status

**Comment by ottodevs** [comment]
Related #223 and #224 
Partially being addressed at: 4705233 and 9c33858
Though it probably needs more work to be polished
