### ISSUE TITLE
Allocations - New Allocation - Have a default "Select an option" item in the options dropdowns + improved validation

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#312]
In the Allocations app, when creating a New Allocation and selecting the checkbox to enable the address book

What happens when you select an option from the dropdown and then select the same option again is it will create a transaction with all options selected, but if the last option is a duplicate it will ignore it and put the transaction through with all but the last option. If the last option selected isn't a duplicate, all options are passed through as expected.

We need to improve this behavior so the UX is more intuitive:

We need a blank option in the address book dropdown that says `Select an entry` - this will be the default option displayed. Whenever the user clicks the plus icon, it should say `Select an entry` in the dropdown.

If entry `Yalda` is selected for the first option, then selected again for the second option, it should reset to `Select an entry`

**Nice to have**
It should also display some kind of tooltip validation message that `The same option cannot be selected twice.` similar to this error style seen in Aragon apps:

![image](https://user-images.githubusercontent.com/2584493/51555806-5af6dc00-1e2d-11e9-91bb-c4ba11b0e909.png)

**Comment by topocount** [comment]
"Select an entry" default dropdown display add in commit e5cdec358a0ad885aec0e95c364e2bc4314613a2
