### ISSUE TITLE
Address book - after removing an entry, the page becomes blank

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#313]
**Steps to reproduce**
- Create 1 or more entries in the Address Book
- Remove one of the entries

**Result**
- The page shows up as blank.

**Expected behavior**
- We need to ensure that if all of the entries are removed, the "no data" use case is displayed
- If there were 2+ entries, and one is removed, then it should display the remaining entries

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/eeaf193d-c710-4b62-9b40-fa78081f109f)

**Comment by ottodevs** [comment]
Hey! Taking this myself if you don't mind @Quazia since it seems to be blocking other issues, the solution seems to be implementing some guards to check if the address exists, for example into getEntry function, trying to provide the solution ASAP :)

**Comment by stellarmagnet** [comment]
I still see this issue. This is what I did:

- Created two address book entries
- Deleted one. It looks okay, like it deleted it
- Then I refreshed the page -- now I get the blank page again

**Comment by Quazia** [comment]
@ottodevs No problem all yours

**Comment by ottodevs** [comment]
The fix seems consistent to me I am not able to reproduce the error since commit d10852b
Please check if it is solved for you also.
