### ISSUE TITLE
Range voting - The description should be the allocation name

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#315]
For both the Vote Row and Side Panel, the description should be the allocation name. Right now it's the account name.

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/e881d68d-1c89-41bc-803b-4a0e4e48414b)

**Comment by Quazia** [comment]
This is really complicated to fix. It's possible but the information is dynamic, and the only place it could potentially exist that the RV would have access to it is in the EVM script.

**Comment by stellarmagnet** [comment]
Why can all other apps forward information to the Voting app, but we cant
forward information to the Range Voting app?
ᐧ

**Comment by stellarmagnet** [comment]
The range voting app is not usable if the user does not know what they are
voting on...
ᐧ

**Comment by Quazia** [comment]
We can forward information to the Range Voting app, but the information being forwarded to the Range Voting app in this situation is much different than the information that's generally forwarded to the Voting app. This is something that requires the cross application modifications and probably the expanded forwarder specification. When forwarding actions to the Voting app, the information regarding what you're voting on isn't user entered data, it's metadata stripped from radspec.

**Comment by stellarmagnet** [comment]
And why can't we also have metadata stripped from radspec in this use case?
ᐧ

**Comment by stellarmagnet** [comment]
Like how does this vote know "10 SWT" or the address i inputted from the finance app?

![image](https://user-images.githubusercontent.com/2584493/51561779-f5aae700-1e3c-11e9-96ec-257701d5e8f2.png)

**Comment by Quazia** [comment]
I'm not saying we can't, I'm saying that this is not as simple as it might seem. The description you've seeing is the scripts description, it's not something the user is setting. I could like try and see if I can set the Radspec description to a single string, pass the string into the setDistribution function, and then manipulate the string but the example you're giving and what need to be done to achieve the result you want are not the same thing. If it's imporant I can try and figure out a way to do it I'm just telling you it's complicated.

**Comment by stellarmagnet** [comment]
Where are the scripts description set?

Trying to understand this radspec thing. From querying Aragon via Github, the only place I see these strings are commented out code beginning with @notice 

https://github.com/aragon/aragon-apps/blob/fa6e64685b7801fb1b0a0f5819b145cb020087e8/apps/finance/contracts/Finance.sol#L202

**Comment by stellarmagnet** [comment]
How does the Voting app know to display these @notice text?
