### ISSUE TITLE
Use Address Badge component throughout our Aragon Apps

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#317]
Anywhere where we are displaying an Ethereum address in our apps, we should use the Address Badge component instead.

Please double check all of our existing apps, and ensure this standard is implemented going forward (for Rewards app etc).

- [ ] Allocations
- [ ] Projects
- [ ] Range Voting
- [ ] Address Book

**Comment by ottodevs** [comment]
Solved at #536
