### ISSUE TITLE
Projects app - Overview tab - Clicking on repo card should navigate to 'Issues' tab with the repo/project filtered

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#323]
Right now clicking on the card does nothing

**Comment by rkzel** [comment]
Two things: making the card clickable and changing Tab to Issues was easy and it improved UX a bit. Changing filters in Issues so that only issues belonging to the clicked Project are shown is not trivial and to to it correctly would require inventing mechanism for passing data between tabs.

**Comment by Quazia** [comment]
Is it possible to connect `selectedIssues` in `Issues.js` to a prop passed in from `AppContent` and then pass a function into `Overview.js` that changes the prop in `AppContent` to the function in `Overview.js`? If you think this strategy would/wouldn't work do you have an idea of how long the issue will take?

**Comment by rkzel** [comment]
After considering few options the fastest one (probably not the most elegant though) was to make activeIndex variable (which was already passing via App itself and connecting Tabs) something more than just a number. So, clicking on Project Card in Overview now switches to Issues and filtering by that project is automagically applied. PR created.
