### ISSUE TITLE
The issue rows in projects app are not consistent with other aragon apps

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#340]
- [x] There are rounded edges, per issue row. Compare how it looks to Range Voting table, etc
- [x] Whenever the browser window shrinks, it overlaps a lot of the text. While I dont expect it to be fully responsive at this stage, we should perhaps at least set a minimum width for the row so it doesn't shrink like that, instead of auto size

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/0d165feb-b886-40f3-a968-95912c7fb309)

**Comment by rkzel** [comment]
Minimum row width can be easily readjusted in the future by the way.

**Comment by stellarmagnet** [comment]
First item still exists, created new ticket #752. Closing this.
