### ISSUE TITLE
Accounts with long names are shifting off page

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#346]
1) We should truncate after 2 lines
2) Ensure that the balance/limit stay within the card and are always in the same location, regardless of if the account name is 1 or 2 lines
3) This is related to #398

![image](https://user-images.githubusercontent.com/2584493/52494281-e2827000-2bcd-11e9-99f9-24d54749c005.png)

**Comment by stellarmagnet** [comment]
@rkzel I think it seems it wasn't clear what issue I was talking about. Please refer to the screenshot above.

Related to #398

**Comment by rkzel** [comment]
A-ha, I fixed the wrong problem then ;) Ein moment...
