### ISSUE TITLE
If I already have a repo connected to my projects app, this repo should not be displayed in the "New Project" panel 

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#351]
If I already have a repo connected to my projects app, this repo should not be displayed in the "New Project" panel whenever I try to add a subsequent project.

Steps to reproduce:
1) Navigate to New Project, select a repo to connect it to Projects app
2) Navigate to New Project again. You will see that your currently connected repo is still being displayed.

Note: in my previous designs, this was a checkbox selection, and previously connected repos would show up as a checkbox that has been checked off, and you cant click on it. But with the radio button route, we probably should just not display them at all.

**Comment by Quazia** [comment]
Can you explain how to duplicate this issue? Is this just a matter of making sure repos that have already been added arn't displayed?

**Comment by stellarmagnet** [comment]
@Quazia yes that's what I mean. I just updated the ticket for clarity
