### ISSUE TITLE
New bounty: bounty value is not being properly calculated

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#373]
The value is not being properly calculated/displayed.

I thought @rkzel had gotten this working before. Please review with @ottodevs to see what this is all about.

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/902faa37-dae8-46af-99d6-2a6ff8a1c0ac)

**Comment by Quazia** [comment]
Is this just a rounding issue? If it's just rounding this should be pretty easy to fix.

**Comment by stellarmagnet** [comment]
No, for some reason the default hourly rate is 30.01.
The math should be Hourly Rate * Experience Level * Hours.

It's not doing that properly

**Comment by stellarmagnet** [comment]
Whenever we do QA for fixing this, please test it twice:

Using defaults, then in the same instance, update the settings and then allocate bounties again. We need to make sure updates to the settings are refleted.

**Comment by ottodevs** [comment]
Tested following the mentioned steps, there was an inconsistency with baseRate being saved at a value but read at the same value divided by 100, that was changing the Settings input by the user, causing a malfunction.
I applied a fix to that.
