### ISSUE TITLE
App state issues

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/planning-suite#374]
These are all some-what related, especially the two application state issues. 

Converting each app over to use a store will probably resolve a lot of these issues. Even when there's proper event handling to ensure removal, as soon as you have addition and removal the concurrency issues start to become present.

**Comment by stellarmagnet** [comment]
@Quazia I'm also seeing this for the projects app - previously connected repos are disappearing

**Comment by Quazia** [comment]
If anybody makes progress with the store or any of the individual issues update the epic please.
