### ISSUE TITLE
Sometimes when I add many address book entries at once, the previously inputted data is displayed

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#376]
Sometimes when I add many address book entries at once, the previously inputted data is displayed in the New Entity panel. 

 This behavior for when this occurs is inconsistent.

Expected: The fields should not be pre-populated

**Comment by Quazia** [comment]
This is most likely a concurrency issue and would be resolved by using the store.

**Comment by Quazia** [comment]
@stellarmagnet I'm a little confused about this cause it's tagged Projects, could you give an idea of exactly the page that's causing the problem?

**Comment by stellarmagnet** [comment]
this is address book, sorry - my fingers slipped when applying labels, @Quazia 

It occurs in the "New Entity" side panel in Address Book
