### ISSUE TITLE
M2 Code Review Changes

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/planning-suite#385]
- [x] a. Ensure props are never being set directly (check all the forms from allocations, should be resolved there may be other places this is relevant)
- [x] b. Check for unnecessary setState calls in NewAllocation.js panel
- [x] c. Fix any direct state manipulation to use setState (NewAllocation.js:88)
- [x] d. Remove payable with just revert from Allocations.sol
- [ ] e. ~~Double check Projects.sol logic and see if anything can be removed, check consistent id usage~~ [created #764 to track]
- [x] f. Move all state declarations to before functions
- [x] g. Switch to using the aragonUI checkbox
- [x] h. Switch to ternary for NewAllocation:237
- [x] i. Add initialize flow to address book
- [x]  j. Look at sync entries in allocations script.js
- [x] k. remove combine latest from allocations script.js
- [ ] L. Look into using store over events/state
- [x] m. Add EXECUTE_PAYOUT_ROLE to runPayout
- [x] n. Look at projects SettingsInput.js
- [x] o. rename apps/projects/app/components/Shared/assets/components/NewProject.js as IconNewProject.js
- [x] p. rename apps/projects/app/components/Shared/assets/components/ArrowDown.js as IconArrowDown.js

For further clarification on the items above, look at the reviews located at: 

- https://github.com/spacedecentral/planning-suite/pull/285
- https://github.com/spacedecentral/planning-suite/pull/254
- https://github.com/spacedecentral/planning-suite/pull/257

Most issues should be a fairly quick check and resolution, feel free to grab these fixes if you're handling a larger issues in the same part of the code. Fixes should be roughly grouped by the part of code effected. A lot of the issues with the Allocations dropdowns etc *should* be fixed but let's double check and make sure before checking off.

**Comment by stellarmagnet** [comment]
@Quazia are we sure about this?  "rename apps/projects/app/components/Shared/assets/components/ArrowDown.js as IconNewProject.js"
