### ISSUE TITLE
New issue - Project should be a required field

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#400]

**Comment by rkzel** [comment]
I added that little blue star, although... removing "select repo" as the first dropdown item made sense. it's self-evident anyway?

**Comment by Quazia** [comment]
Looks good, resolved with PR #412

**Comment by stellarmagnet** [comment]
@rkzel now i don't see "select a repo" when I am creating an issue and there are repos...

Is it difficult to just hide the New Issue button if they dont have any projects added?
