### ISSUE TITLE
Hide description field in bounty allocation panel

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#402]
- [ ] Hide description field in bounty allocation panel
- [ ] In the Range Voting app we will have to display it as `Range Vote #[num] - Bounty Allocation`

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/ec7b798f-96a4-4bc4-b487-fed0acea68d8)

**Comment by Quazia** [comment]
Resolved in pull for issue #296
