### ISSUE TITLE
Update the bounty amount badge style on Issue Detail to match Issue list

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#466]
The style of bounty badge on Issue Detail to match Issue list.

Additionally it doesnt seem like it's populating the proper data source yet

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/19570134-b574-48db-a8d9-63f147ddca66)

**Comment by ottodevs** [comment]
This seems duplicated of #403 first task:

>  Update the FE for the bounty amount on the View Issue page to be consistent

**Comment by rkzel** [comment]
It was part of #403, yes.
