### ISSUE TITLE
npm i when ipfs download failed

### ISSUE THREAD

**Issue by rectinajh** [AutarkLabs/planning-suite#475]
npm i

Downloading https://dist.ipfs.io/go-ipfs/v0.4.17/go-ipfs_v0.4.17_darwin-amd64.tar.gz

Error: connect ETIMEDOUT 69.171.240.27:443
Download failed!

**Comment by Quazia** [comment]
Going to need more information, it looks like this issue is more related to a potential internet issue or an issue loading the IPFS dependency so without the ability to replicate the issue it'll be difficult to troubleshoot.

**Comment by ottodevs** [comment]
Hi! Thanks for reporting, closing for the related https://github.com/aragon/aragon-cli/issues/381 hopefully it will be fixed soon, in the meanwhile I can only recommend to keep trying but seems ipfs.io servers are having availability issues
