### ISSUE TITLE
Revisit the terminology for the various bounty statuses

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#480]
* undefined--> Display: "**Not funded**"
* 'new'-->'funded'--> Display: "**Accepting applicants**", color of bounty (Green), context menu options (Request Assignment) 
* 'review-applicants'-->Display: "**Pending application review**", color of bounty (Green),  context menu options (Request Assignment, Review Application) 
* 'submit-work'-->'in-progress'--> Display: "**Work in progress**", color of bounty (Yellow), context menu options (Submit work)
* 'review-work'-->Display: "**Work ready for review**", color of bounty (Yellow), context menu options (Review Work)
* 'finished'-->'fulfilled'--> Display: "**Fulfilled**", color of bounty (Grey), context menu (hidden)

If work is rejected, reset to 'new'.

TBD: need to define how we handle when there are multiple available...

**Comment by stellarmagnet** [comment]
This display text was not implemented.

**Comment by stellarmagnet** [comment]
@Schwartz10 since you will be working on #502, can you review the requirements in this ticket in parallel and make sure we have coded the proper display text per status? the 'in-progress' etc. was supposed to be more the backend identifier, my ticket perhaps wasn't very clear.

**Comment by Schwartz10** [comment]
Are there any designs I could look at for reference of where this text appears? Each individual issue row? In the issue detail page? Both?
