### ISSUE TITLE
Settings tab will not scroll

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#484]
I have a small monitor, and I cannot scroll down the Settings tab. There is no scroll bar.

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/254ebf0c-cff9-408b-93d9-a65096fc4b15)

**Comment by ottodevs** [comment]
Solved at 2d5f7304b3080a3f006afecabe0863204a9cd1f4
