### ISSUE TITLE
Update currencies in Limit dropdown

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#493]
Perhaps we just have ETH and the tokens in the vault?

The selected currency should be displayed in the "Account" card.

Only one currency type for now, as far as what we support in the UI.

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/9f0689cc-ae88-4e23-a36a-92e39e708475)

**Comment by Quazia** [comment]
This is blocked by issue 151
