### ISSUE TITLE
Update base rate / bounty currency in Settings tab

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#500]
Remove the "Bounty currency" section, yet retain the logic for the drop down there

in the Base Rate section, replace "DAI" with the copy pasta of the dropdown 

end result: MAGIC!

**Comment by rkzel** [comment]
Does this look better?

![settings](https://user-images.githubusercontent.com/34452131/53772255-a517b680-3edd-11e9-9b90-cf27b5047572.png)

**Comment by stellarmagnet** [comment]
It should be below experience level. Delete “select” as well and combine
the drop down with the input, like in the New Allocation token transfer
panel
