### ISSUE TITLE
bug report:npm i --verbose,alway occured download ipfs failed

### ISSUE THREAD

**Issue by rectinajh** [AutarkLabs/planning-suite#514]
Downloading https://dist.ipfs.io/go-ipfs/v0.4.17/go-ipfs_v0.4.17_linux-amd64.tar.gz
Error: connect ECONNREFUSED 31.13.72.54:443
Download failed!

**Comment by ottodevs** [comment]
Hi! Thanks for reporting, seems related to: https://github.com/aragon/aragon-cli/issues/381 hopefully it will be fixed soon, in the meanwhile I can only recommend to keep trying but seems ipfs.io servers are having availability issues

**Comment by ottodevs** [comment]
duplicated #475
