### ISSUE TITLE
Enhance the checkbox interaction for Projects issues rows

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#535]
- [x] When I try to click the checkbox, but my cursor slips sometimes and I click on the issue row instead (and it opens the issue detail view). Suggested change: Make it so the issue detail will open only if you click in this region highlighted in the picture below. We should avoid regions close to checkboxes or action menus. Note: if the context menu is not there, the clickarea should span until the edge of the row.

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/c58e6eb7-71a2-4d36-90bf-14863810052e)

- [x]  The checkboxes are changing size - it should be consistent size. Make sure we are using aragon-ui's checkbox component.
![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/b17c394c-51c9-4aec-8d86-c7c01d3bf1c7)

**Comment by rkzel** [comment]
Checkbox has surrounding space unclickable now. ContextMenu could have similar space around it, but it would be more time consuming right now and CM is much bigger...
