### ISSUE TITLE
Create Front-end Developer Challenge Boilerplate

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/planning-suite#558]
Modify the Aragon React [Kit or non-kit] boilerplate to hold the relevant contract for fulfilling the developer challenge.

**Comment by topocount** [comment]
This is now up here: https://github.com/AutarkLabs/fe-dev-challenge

Right now it loads and the script.js and app.js files are empty. The contract compiles and behaves as expected, and I kept it relaxed, `require`-wise since it might compel the dev to put more checks in the frontend.
