### ISSUE TITLE
I got a problem when i 'npm start'. 

### ISSUE THREAD

**Issue by 1011sh** [AutarkLabs/planning-suite#561]
![2019-03-14 19-27-51屏幕截图](https://user-images.githubusercontent.com/932528/54353601-67f6b580-468f-11e9-81ba-84079cf399e2.png)

**Comment by stellarmagnet** [comment]
@1011sh Try this: npm run clean && npm run clean:build && npm run clean:aragon && npm i && npm run clean:commit && npm start
