### ISSUE TITLE
Ensure aragon signatures use `web3.eth.personal.sign` method to sign arbitrary data

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/planning-suite#565]
This is related to https://github.com/aragon/aragon.js/pull/204 and https://github.com/aragon/aragon.js/issues/124

But in order to get the right signatures, we need to make sure signing data via 3box gives you the same signature as signing data from aragon

The method to use is `web3.eth.personal.sign`

**Comment by Quazia** [comment]
If these _don't_ give the same signature this has the potential to be a higher weight, or create another issue.
