### ISSUE TITLE
Create a separate class as a layer between 3box and the react app

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/planning-suite#566]
The idea of this class is to easily be able to move this out to its own npm module or github repo if we wanted to. It also make it easier to swap out the underlying profile api we use (if we ever want to move off of 3box)

The class should have the following api interface: https://github.com/openworklabs/flock-grant-specs/blob/primary/profile-api/profile-api.md

**Comment by Quazia** [comment]
I'd potentially pad this weight just to give time for build/testing.

**Comment by Schwartz10** [comment]
This can cover QA
