### ISSUE TITLE
Use TabBar component in Projects app

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#593]
When we implement this make sure there is still a white ground behind the tabs.

We don't want it to be like how the Rewards app is rendering (#670).

Should reference the Survey app and Payroll app and follow as closely as possible, although Projects app is more complex due to conditional rendering of action buttons based on github auth state.

**Comment by ottodevs** [comment]
Related to applying this: https://github.com/aragon/aragon-ui/pull/323
