### ISSUE TITLE
Update FE for Settings tab

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#619]
- [x] Rename "Base Rate" to "Bounty Base Rate"
- [ ] Move the "Bounty Deadline" section above "Bounty Contract Address"
- [ ] Make the page responsive

Desktop Design
https://projects.invisionapp.com/d/main#/console/14716432/344998079/preview

Mobile Design
https://projects.invisionapp.com/d/main#/console/14716432/353737286/preview

**Comment by rkzel** [comment]
Current desktop view looks is below - presumably moving sections is not required? Should the "Save" button span entire width of the page? It's kind of weird now...

![settings](https://user-images.githubusercontent.com/34452131/56131763-ad591c00-5f88-11e9-81b2-c2bce0ddead2.png)
