### ISSUE TITLE
Cannot submit a bounty allocation

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#640]
Steps to reproduce:

1) Navigate to the Projects app
2) Select three issues, then "Allocate Bounties"
3) Input the hours per issue. For one of the issues, update the experience level and deadline
4) Hit the submit button.

Behavior: There is no error and no metamask window opens for you to sign the transaction.

**Comment by topocount** [comment]
As discussed, this is likely environmental. Please let me know how you get on after deleting the wrapper with `npm run clean:aragon` and then re-running `npm run clean` and then `npm run start`

**Comment by stellarmagnet** [comment]
Closed, was environment issue, cannot reproduce

**Comment by Schwartz10** [comment]
@stellarmagnet I'm still getting this issue and will investigate

**Comment by Schwartz10** [comment]
Should be fixed in https://github.com/AutarkLabs/planning-suite/pull/655/
