### ISSUE TITLE
Unclear that work has been reviewed 

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/planning-suite#657]
I just went through the process of bountying, submitting work, approving...etc

But after i reviewed the work, when i revisit the issue, it still says review work. When i try and resubmit a review, it says 

```
Action impossible
The action failed to execute. You may not have the required permissions.
```

**Comment by Schwartz10** [comment]
Should note the first transaction appeared to go through properly

**Comment by topocount** [comment]
Are you seeing this in the dev branch, Jon?

**Comment by Schwartz10** [comment]
Have not yet, will try there too.

**Comment by Schwartz10** [comment]
Oh actually, @topocount - I can't test in the dev branch because I can't fetch bounty JSON objects via `ipfs-http-client` without getting the `preflight` errors. So i made those minimal changes to fix the error

**Comment by Schwartz10** [comment]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/12353734/55123145-d9932280-50d7-11e9-8b50-196cd761d553.png">

This time a little bit different of a behavior, the tx went through successfully though
