### ISSUE TITLE
Display proposed bounty allocations in Voting app

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#668]
**User Story**
As a project manager, I want to be able to see a list of the issues and bounty amounts when a Bounty Allocation proposal is in the Voting app.

**Potential Solutions**
We should consider having the user sign two transactions during the Bounty Allocation flow so we are able to display the funding proposal in the Voting app. 

The first action will have an open permission where token holders of the DAO (or Any Account) are able to sign like GENERATE_FUNDING_PROPOSAL. Since linking to an app's tab/object may not be possible now, we might want this to generate an HTML file that would be pinned to IPFS.

Hence the Bounty Allocation will have an additional metadata field (bountyProposalData) which is the IPFS hash and this is generated when the action that doesn't go through the voting app is triggered.

The second transaction they have to sign is the one we have today for the bounty allocation. The radspec for action that is being forwarded to the Voting app would then be `Fund bounties for '<Bounty allocation description>: ipfsgateway:bountyProposalData'`

**Comment by Quazia** [comment]
The potential solution here is only temporary, long term this should be handled through application state streams synced through the client, and the forwarder API. Do we want to pursue a short term solution or prioritize this as a future upgrade based on SDK changes?

**Comment by stellarmagnet** [comment]
How long does the short term solution take? Our early adopters the Aragon
coop will probably find this feature useful in near term
