### ISSUE TITLE
0 eth showing up in Range Voting

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#685]
![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/bdb57e85-448d-4c38-b274-4d5290d902d5)

**Comment by Quazia** [comment]
Going to double check this is working in the allocations-rework branch and fix it if it's not.

**Comment by Quazia** [comment]
Resolved in allocations-rework
