### ISSUE TITLE
Update "Minimum of 5% is required"

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#686]
1) The min. support percentage is hard coded now and we need to update this so it displays the data in the contract.

2) We should also test to see if it does actually work when the min. support is set to 5%

3) This line of text should not appear for the following use cases:
- [ ] Issue curation votes
- [ ] When the min. support is set to 0

**Comment by Quazia** [comment]
Resolved in allocation-rework branch
