### ISSUE TITLE
Bounty allocations are removed from issues after clearing cache

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#688]
1) select some issues
2) allocate bounties to the issues
3) clear application cache

Result: the issues no longer have bounties

Expected: the issues should retain their bounties after cache is cleared

**Comment by Schwartz10** [comment]
@stellarmagnet i get this randomly even without clearing cache too

**Comment by Schwartz10** [comment]
I can't replicate this issue - https://github.com/AutarkLabs/planning-suite/issues/688 but i do get really incosistent behavior with bounty statuses. Sometimes allocations will show, sometimes not, sometimes the right status shows, other times not..

**Comment by Schwartz10** [comment]
1. Integrate with a repository with >1 issue
2. Fund 2 issues
3. refresh the page, verify the status is correct
4. Change the status of one issue (request assignment)
5. The status on the other bounty disappears
