### ISSUE TITLE
Should not be able to review an application with 0 applicatants

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/planning-suite#698]
This throws an error when yo utry to review: not sure how i got here.

![image.png](https://images.zenhubusercontent.com/5c6af7f4ad92af7fa5dc3a7b/af13476f-ff2d-4b27-bf11-5b97969f055a)

**Comment by stellarmagnet** [comment]
@Schwartz10 does this still exist?

**Comment by stellarmagnet** [comment]
Closing until this is encountered again
