### ISSUE TITLE
Show bounty amount for fulfilled bounties

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#747]
Areas affected:
- [ ] Issue detail
- [ ] Issue row 
![image](https://user-images.githubusercontent.com/2584493/55845689-39abaf00-5b43-11e9-9ed7-28450eed1300.png)

**Comment by Quazia** [comment]
This requires setting the local issue instance in Projects.sol at time of fulfillment and conditionally pulling the amount from local state vs StandardBounties state based on fulfillment.
