### ISSUE TITLE
Cannot specify Bounty Base Rate

### ISSUE THREAD

**Issue by lkngtn** [AutarkLabs/planning-suite#801]
I've been testing out the projects app and seem to have run into an issue. Here is what I'm trying to do... 

I want to have an organization where finance is connected to vault A, and projects is connected to vault B. This way tokens can be moved from vault A to vault B and subject to the finance apps permissions and budgeting, and then the fund bounties permission can not require a vote because it can only access pre-allocated/budgeted funds. 

Unfortunately, Im not able to get projects to work because I dont seem to be able to specify the default rate. 

![image](https://user-images.githubusercontent.com/4986634/56474793-f4458680-644c-11e9-8f89-f4ba5e7b9ffc.png)

This message indicates that the token must be in finance and it is...

![image](https://user-images.githubusercontent.com/4986634/56474798-032c3900-644d-11e9-8bb2-62732c7dcdbf.png)

The token is also in the vault which the projects app was initialized with. 

![image](https://user-images.githubusercontent.com/4986634/56474807-1939f980-644d-11e9-98e9-e16a9fcd8db9.png)

These were the steps I used to setup this organization:

#### Install a new instance of the Vault
```
	dao --environment aragon:rinkeby install btest.aragonid.eth vault
```

```
	New Vault Addres: 0xca43b5cc5ecd34e27d97CBbAc4c3a6f90EC6bE9c
```

We can leave this vault as is for now it will be necessary for initializing the Projects app. 

#### Install the address book app
```
	dao --environment aragon:rinkeby install btest.aragonid.eth address-book-staging.open.aragonpm.eth
```

```
	Adress Book Address: 0x2d0bEE85e69294D12CE2909bA11Eb254a2eB4554
```
#### Install Dot Voting App 

The Dot Voting app is used by both Autarks Allocations app and the Projects app. Dot Voting allows token holders to prioritize between multiple options by distributing votes across multiple options. 

```	
dao --environment aragon:rinkeby install btest.aragonid.eth dot-voting-staging.open.aragonpm.eth --app-init-args [AddressBook] [MinimeToken] 500000000000000000 50000000000000000 3600

```

```
Dot Voting Address: 0x7452C7895d87737e53eD78121dB770F67dF42203
```
#### Install the Projects app

The projects app allows an organization to manage a bounties workflow using github and the standard bounties contracts. Funding for bounties is taken from a vault, and since these transfers will not show up in finance or be subject to finances budgeting functionality it is best to associate projects with a different vault than what finance is associated with, then transfer funds from finance into the bounties pot periodically. 
```
	dao --environment aragon:rinkeby install btest.aragonid.eth projects-staging.open.aragonpm.eth --app-init-args 0xcac024cb2ad5f22c3e92053b95c89f69442952d8 0xca43b5cc5ecd34e27d97CBbAc4c3a6f90EC6bE9c 0xE3d31248A3003A55799d71BfD8F17347BD50A50D
```

```
	Projects Address: 0x3f057F908Ff2CD7784316c96d336A7b7D9E37712
```
#### Permissions

In order to make projects and dot voting appear in the UI we need to initialize some permissions. I typically only initialize one permission from the command line for each app just to have them show up in the UI, then do the rest in permissions. 

![image](https://user-images.githubusercontent.com/4986634/56474783-adf02780-644c-11e9-90ad-d3f4ede3cbeb.png)

It is not totally clear from this summary, but projects and finance are accessing different vault instances.

**Comment by stellarmagnet** [comment]
Short term solution that will address this for the default/init token here: https://github.com/AutarkLabs/planning-suite/commit/bf370105fd2946fd2481c02bca62d0d81108d219

[Yalda to review]
