### ISSUE TITLE
Issues with Projects app in dev branch

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#805]
Projects app isn't working to spec (features that used to previously work), these are the main issues:

- [x] The "New Issue" button is not being displayed whenever I have connected Projects
- [x] Whenever I select multiple issues, the "Actions” button never becomes enabled. 
- [x] The conditional rendering of "Sign in with Github" is not correct

**Comment by Quazia** [comment]
Bullet point #2 resolved in #790

**Comment by ottodevs** [comment]
Done with the fix of the rest of bullet points
