### ISSUE TITLE
Dot Voting app not showing side panel for closed votes on safari

### ISSUE THREAD

**Issue by 0xGabi** [AutarkLabs/planning-suite#819]
I was looking the rinkeby dao and I experienced this error on safari (macOS):
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/9082013/56629747-d16dca80-6624-11e9-9443-055d3ba00c87.png">

```
[Warning] [blocked] The page at https://rinkeby.aragon.org/#/dune.aragonid.eth/0x796ce2aa4d42316f4ad0b365a3d90d0743edcfb7 was not allowed to run insecure content from ws://127.0.0.1:1248/. (src.5d2a3001.js, line 891)
```

Note: This works as expected on Brave.

**Comment by stellarmagnet** [comment]
I think this should be fixed now, can you confirm @0xGabi ?

**Comment by 0xGabi** [comment]
Yes, it's working now 👍
