### ISSUE TITLE
cypress web3 provider

### ISSUE THREAD

**Issue by rkzel** [AutarkLabs/planning-suite#820]
Cypress has simple web3 client injected into test script to provide interface to ethereum. It works for some apps, but it breaks on Dot Voting (

It it not enough. One problem is Dot Voting transactions breaking:

Error signing the transaction
Woops, something went wrong. The transaction hasn’t been signed and no tokens have been sent.
Error: “VM Exception while processing transaction: revert { "0xae68b4c2b2dfefa9582c1131635b0fd84d66fb058910f3222915f0364eda4de9": {
  "error": "revert",
  "program_counter": 614,
  "return": "0x0"
}, "stack": "RuntimeError: VM Exception while processing transaction: revert

The other problem (encountered so far) is that in Projects we use global 'web3' provided by MetaMask, and it doesn't work with the Cypress web3 client we use.

We can investigate further current client, we can look for alternatives, or we can use MetaMask in Cypress.

**Comment by topocount** [comment]
A workaround of providing a hard-coded `gas` value in the app-level function call has been implemented for the vote function in branch 820. The root problem of the gas not calculating automatically will be tracked in issue #849 going forward.
