### ISSUE TITLE
Expanded address in Allocations is fuzzy

### ISSUE THREAD

**Issue by julianbrooks** [AutarkLabs/planning-suite#829]
see attached image for demo
Firefox browser
GNU/Linux OS
![allocation expand fuzzy](https://user-images.githubusercontent.com/2914733/56869365-c38ac180-69f7-11e9-8926-3a25b27cc7b5.png)

**Comment by stellarmagnet** [comment]
This should be covered once #917 is completed, so I am closing this ticket.
