### ISSUE TITLE
Setup an IPFS node

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#832]
We need a sustainable way to pin our app's IPFS hashes, now that we have a server we should have our own cluster. This issue only covers the initial setup, complex configuration and connecting our applications to the node are out of the scope for this issue.

**Comment by rkzel** [comment]
IPFS node has been set up, and basic documentation saved:

https://docs.google.com/document/d/1_iAttrkCQfW-5CZpqQ38ioAyt2EGtfIw9F1psiGvAgo

Serious documentation is being created in another ticket, #925.

The node is definitely reachable from 'aragon apm' point of view, but publishing to it like:

aragon apm publish patch --debug --apm.ipfs.rpc https://ipfs.autark.xyz/ipfs/ --ipfs-check false

(that's in address book) fails on:

POST /api/v0/add?recursive=true&stream-channels=true HTTP/1.1" 413

413 is "body too large", and the limit is set to 32M, so... there's something going on.

**Comment by rkzel** [comment]
Current problem is:
1. 'apm publish' creates 20MB of dist files and sends it to nginx acting as reverse proxy for IPFS daemon,
2. nginx sends the files upstream to ipfs daemon (confirmed with tcpdump),
3. ipfs receives the files, but does not respond properly, causing nginx to log timeout error msg.

I'm talking to IPFS people on IRC, trying what they suggest. Next step: replacing nginx with haproxy, then installing ipfs cluster.
