### ISSUE TITLE
Setup cron job to run through aragon ipfs propagate

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#833]
We should set up a job to do aragon ipfs propagate once a day for our staging and rinkeby hashes, just in case.

**Comment by rkzel** [comment]
Ok, the cronjob is set up and mentioned in Server Farm doc:

https://docs.google.com/document/d/1_iAttrkCQfW-5CZpqQ38ioAyt2EGtfIw9F1psiGvAgo/edit

Scheduled to run daily.
