### ISSUE TITLE
Open Profile App Q's

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/planning-suite#842]
- [x] What additional fields should be on the left informational panel?
- [x] Should the right panel be reserved for DAOs only? Or other organizations can go there too? How does a user add organizations? What should this process look like?

**Comment by Schwartz10** [comment]
[ ] How does a user invoke the signature request (aka a login/create profile button)
[ ] How does a user upload a cover photo? 
[ ] How does a user upload an avatar?
[ ] what does an empty profile state look like?
[ ] how does a user upload a new education, work history, or organization? (assuming modal)
[ ] Where does a user see the social verification instructions? Another modal?

**Comment by stellarmagnet** [comment]
Done: https://docs.google.com/document/d/1Vluc0R8qEgtxv8m2GpC6a1KqAfZ2sqLGCJGJMcTRiV4/edit#heading=h.18wdvf9e5w8b

Let me know if everything is covered, if so, please close this ticket.
