### ISSUE TITLE
Reward Summary text seems wrong

### ISSUE THREAD

**Issue by lkngtn** [AutarkLabs/planning-suite#848]
The reward text appears to describe a "merit" reward despite being a "dividend"

The time also appears to be incorrect (should be the default 7 days after period ends). 

<img width="450" alt="image" src="https://user-images.githubusercontent.com/4986634/56988510-3a41cf00-6b5e-11e9-8463-ba4fbb4e01d6.png">

**Comment by Quazia** [comment]
Thanks for the catch!
