### ISSUE TITLE
Perform thorough, manual browser testing

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#877]
We need to do a really detailed manual test across Chrome (or Brave) AND Firefox.

Have the console open while testing and make sure we track any errors

- [x] Update the test script so it is more comprehensive (include the items i describe below...)
https://docs.google.com/document/d/1mhcqthARp2-pb1j5SXpwdMiTW91LqZl9gJMYwOHmh5c/edit#heading=h.x6s7caf62jyz
- [x] Include Rewards in the testing
- [x] Test adding repos with > 100 issues (like planning-suite); ensure scroll works
- [x] Test creating Allocations when the address book isn't being used
- [x] Test executing Issue Curation votes, then return to Projects app
- [x] Verify that allocation amounts per option are accurate
- [x] Test in Firefox
- [x]  Really try the extremes to break things: 
   - [x] try to fund 30 issues, **Our max is 5**
   - [x] change every possible projects setting, 
   - [x] verify settings are updating properly
   - [x] try to curate 30 issues (what is our limit, anyway?)
- [x]  Try to create various kinds of rewards, make sure the text is properly displayed and that they distribute properly. Make sure all tabs and panels open in both browsers
- [x]  Make notes of where we can optimize the gas or the radspec
- [x] Sometimes a CORS error will block the app from loading data. We need to capture when this occurs and try to hone in on what the cause is. #663

**Comment by topocount** [comment]
Regarding the CORS errors: They seem to be side-effects that are thrown when other errors occur, specifically in projects right now. I have yet to come across a standalone CORS error
