### ISSUE TITLE
FilterBar overlays Issue actions Dropdown

### ISSUE THREAD

**Issue by topocount** [AutarkLabs/planning-suite#885]
Because the filterbar is rendered on top of the actions dropdown, it's not possible to assign bounties to issues in the dev branch
![image.png](https://images.zenhubusercontent.com/5acc29064b5806bc2bce6855/0933ee06-0b4d-43e9-92bf-f88abc9c103b)

**Comment by Quazia** [comment]
Should be addressed in projects-hot-fix
