### ISSUE TITLE
attempting to use regex in the searchbox throws an ErrorBoundary

### ISSUE THREAD

**Issue by topocount** [AutarkLabs/planning-suite#901]
When attempting to enter any advanced search text like a single asterisk: `*`, an error boundary is thrown. We should sanitize inputs to prevent the error boundary (show below) from appearing when someone is trying to compose a query:

![image](https://user-images.githubusercontent.com/17910833/57416424-2bd66180-71b5-11e9-8f84-0bd86419c1b6.png)

**Comment by chadoh** [comment]
What kind of search do we want? Do we want regex search like this?

<img width="513" alt="Screen Shot 2019-06-07 at 10 46 48" src="https://user-images.githubusercontent.com/221614/59112844-d4d9be80-8911-11e9-8bd7-837347e8e2ab.png">

**Comment by chadoh** [comment]
GitHub's approach is to use exact string matching; no regex search. I'll implement the same.
