### ISSUE TITLE
Projects: Issue Detail: issue text should not overflow

### ISSUE THREAD

**Issue by ottodevs** [AutarkLabs/planning-suite#906]
We need to solve this cosmetic issue:

![image](https://user-images.githubusercontent.com/5030059/57543274-37ac5a00-7354-11e9-9fdd-11da71ac7563.png)

**Comment by stellarmagnet** [comment]
This seems related to our markdown stylesheet -- so if we use the same stylesheet in Home app, same issue will occur. So it makes sense to resolve this this week.
