### ISSUE TITLE
Improve the filter bar design [final]

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#915]
The selected/hover state of the overflow icon does not match the designs.

Additionally, when i hover over the "..." icon it seems to also give a dropshadow to the bar (instead of adding the grey background to the icon), and this dropdown stretches to the "sort by" section, which is not desirable. There should not be any dropshadow in the filter bar for the '...' icon; on hover or active state, it should look like in the design (the icon has a grey background)

Considering the filter bar has not been implemented to the design, next time please share a video in the design channel before submitting the pull request.

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/3fc57fdb-5b3b-4e04-8ed9-8c6984415e9e)

**Comment by rkzel** [comment]
This is done, and the video has been shared...
