### ISSUE TITLE
Uptake new markdown stylesheet in Projects app

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#955]
The Issue Detail page of the Projects app uses a markdown stylesheet. We should use the same stylesheet developed for the home app.

[@chadoh - i updated, is this enough detail?]

**Comment by chadoh** [comment]
@stellarmagnet can you provide a description, please?

**Comment by chadoh** [comment]
That description looks great, @stellarmagnet! This issue has been addressed and the fix has been merged.
