### ISSUE TITLE
Projects UI tweaks

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/planning-suite#966]
- [x] Get rid of the rounded edges for the inner rows - It’s like two 1px borders are stacked and the border is 2px now. 
- [x] Truncate issue name after two lines
- [ ] Fix `Sort by` menu so it doesn't clip. It should say "Sort" instead. Also I like the Github way of each sort option fully explaining the direction. (see below)
![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/b2f40b39-0d1f-4e05-af55-5f0a3f6c68e3)
![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/eab34d6f-4df6-4227-a04a-fc483b3eac83)
![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/899d08b4-7f57-47c8-b710-36533dcb30e5)

**Comment by chadoh** [comment]
> Get rid of the rounded edges for the inner rows - It’s like two 1px borders are stacked and the border is 2px now.

I think this was only a problem that started with [the `react-window` effort](https://github.com/AutarkLabs/planning-suite/pull/904), and it has been addressed there.
