### ISSUE TITLE
Replace nginx with haproxy

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/planning-suite#981]
The idea here is to isolate nginx out of the architecture to see if the current problems have to deal with nginx, or something else (e.g., IPFS Config, publish command...etc)

**Comment by Schwartz10** [comment]
We think it's most likely that the publish command is broken (or not working well with the proxy server, our current setup...etc).

One reason for evidence is here:

logs from publish script:

```
`Building frontend [completed]
Prepare files for publishing [started]
Prepare files for publishing [completed]
Generate application artifact [started]
Generate application artifact [skipped]
→ Using existent artifact
Publish address-book.aragonpm.eth [started]
Generating transaction [started]
→ Fetching DAO at 0x983b4Df4E8458D56CFDC51B9d2149381AF80308A...
Generating transaction [completed]
Sending transaction [started]
→ Waiting for transaction to be mined...
Sending transaction [completed]
Publish address-book.aragonpm.eth [completed]
Fetch published repo [started]
Fetch published repo [completed]

 ✔️ Successfully published address-book.aragonpm.eth v8.0.0: 
 ℹ️ Contract address: 0x0f407B6532BB4092638Ad5CEd2b17BD34d521402
 ℹ️ Content (ipfs): QmTUAPRjZLXeVcXfcWWdRnv2ArkhvcVYWDxKxeRoRGZZ5T
 ℹ️ Transaction hash: 0x488d2d894fc2f07d7719a7f3fe2e63ceeafe41515597f3604afe9db845e435be
 ❯ Published directory: /tmp/tmp-20432Zu6MIDjWB002
```

The important part is here:

```
 ℹ️ Transaction hash: 0x488d2d894fc2f07d7719a7f3fe2e63ceeafe41515597f3604afe9db845e435be
```

from this command: `aragon apm publish major --debug --apm.ipfs.rpc https://ipfs.autark.xyz:5001 --ipfs-check false --files dist/`

It appears as though the upload went successfully, but what under the hood, the IPFS hash that's returned represents a single file, rather than the proper file directory. In order for this command to work properly, the returned IPFS hash should represent the `dist/` folder

**Comment by rkzel** [comment]
haproxy seems to be working. AB, allocations and projects were published without any visible problem. Conclusion: nginx is the problem, although it is still not clear whether it is apm<->nginx or nginx<->ipfs side... In any case this ticket can now be closed.
