### ISSUE TITLE
Create a new `create-aragon-app` for testing publishing

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/planning-suite#984]
The entire planning suite repository is really big, and problems with publishing are harder to debug with such a big operation.

This ticket is for creating a new, simple aragon app, and using it for publishing testing

**Comment by rkzel** [comment]
I've created basic app and DAO. Tested publishing to our IPFS via haproxy and nginx. Results: haproxy worked, nginx did not. And successful publishing looks like this:
![counterapp](https://user-images.githubusercontent.com/34452131/59475106-11457700-8e4a-11e9-893a-360fdc47c014.png)
